/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apppartido;
import core.DirectorTecnicoController;
import core.EquipoController;
import core.JugadoresController;

import core.RutUtil;
import core.mensajeUtil;
import javax.swing.ComboBoxModel;
import javax.swing.JList;
import javax.swing.WindowConstants;
import modelo.*;
/**
 *
 * @author Miguel Castillo
 */
public class appPartido extends javax.swing.JFrame {

    /**
     * Creates new form appPartido
     */
    public appPartido() {
        initComponents();
        cargaInicial();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane6 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldNombreEquipo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxDirectorTecnico = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListEquipos = new javax.swing.JList<>();
        jButton6 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableJugadores1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldrutJugador = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNombres = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldApellidoPat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldApellidoMat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldrutNumero = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jComboBoxEquipo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jCheckBoxTitular = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableJugadores = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldNombreDt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldApellidoDt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldApellidoMatDt = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListDt = new javax.swing.JList<>();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldRutDt = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jComboBoxEquipoVs1 = new javax.swing.JComboBox<>();
        jComboBoxEquipoVs2 = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jListJugadorPartido1 = new javax.swing.JList<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        jListJugadorPartido2 = new javax.swing.JList<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBoxPartidoJugado = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel8.setText("Nombre Equipo");

        jComboBoxDirectorTecnico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setText("Director Técnico");

        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jListEquipos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListEquiposValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(jListEquipos);

        jButton6.setText("Quita");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTableJugadores1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rut", "Nombre", "numero", "Tipo", "Equipo", "Titular"
            }
        ));
        jScrollPane5.setViewportView(jTableJugadores1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldNombreEquipo)
                                .addComponent(jComboBoxDirectorTecnico, 0, 258, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton2))))
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)))
                .addContainerGap(224, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxDirectorTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton6))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Equipo", jPanel1);

        jTextFieldrutJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldrutJugadorActionPerformed(evt);
            }
        });

        jLabel1.setText("Rut");

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombres");

        jTextFieldNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombresActionPerformed(evt);
            }
        });

        jLabel3.setText("Apellido Pat.");

        jTextFieldApellidoPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellidoPatActionPerformed(evt);
            }
        });

        jLabel4.setText("Apellido Mat.");

        jTextFieldApellidoMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellidoMatActionPerformed(evt);
            }
        });

        jLabel5.setText("Número");

        jTextFieldrutNumero.setText("0");
        jTextFieldrutNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldrutNumeroActionPerformed(evt);
            }
        });

        jLabel6.setText("Tipo");

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arquero", "Defensa", "Volante", "Delantero" }));
        jComboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoActionPerformed(evt);
            }
        });

        jComboBoxEquipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Equipo");

        jCheckBoxTitular.setText("Titular");
        jCheckBoxTitular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTitularActionPerformed(evt);
            }
        });

        jTableJugadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rut", "Nombre", "numero", "Tipo", "Equipo", "Titular"
            }
        )
    );
    jScrollPane2.setViewportView(jTableJugadores);

    jButton5.setText("Quitar");
    jButton5.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton5ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jCheckBoxTitular)
                        .addComponent(jComboBoxEquipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldrutNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                        .addComponent(jTextFieldApellidoMat, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                        .addComponent(jTextFieldApellidoPat, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                        .addComponent(jTextFieldNombres, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                        .addComponent(jComboBoxTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldrutJugador))
                    .addGap(24, 24, 24)
                    .addComponent(jButton1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton5)
                    .addGap(0, 0, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)))
            .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(26, 26, 26)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jTextFieldrutJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jTextFieldNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jTextFieldApellidoPat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jTextFieldApellidoMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel5))
                .addComponent(jTextFieldrutNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel6)
                .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jComboBoxEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel7))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jCheckBoxTitular)
                .addComponent(jButton1)
                .addComponent(jButton5))
            .addGap(18, 18, 18)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
            .addContainerGap())
    );

    jTabbedPane1.addTab("Jugadores", jPanel2);

    jTable2.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null, null, null, null}
        },
        new String [] {
            "POS", "EQUIPO", "PTOS", "PJ", "PG", "PE", "PP", "GF", "GC", "DG"
        }
    ));
    jScrollPane3.setViewportView(jTable2);

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
            .addContainerGap())
    );
    jPanel4Layout.setVerticalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
            .addContainerGap())
    );

    jTabbedPane1.addTab("Tabla Posicion", jPanel4);

    jLabel10.setText("Nombre DT");

    jLabel11.setText("Apellido Pat.");

    jLabel12.setText("Apellido Mat.");

    jButton4.setText("Agregar");
    jButton4.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton4ActionPerformed(evt);
        }
    });

    jListDt.setModel(new javax.swing.AbstractListModel<String>() {
        String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
        public int getSize() { return strings.length; }
        public String getElementAt(int i) { return strings[i]; }
    });
    jListDt.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            jListDtFocusGained(evt);
        }
    });
    jListDt.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
        public void propertyChange(java.beans.PropertyChangeEvent evt) {
            jListDtPropertyChange(evt);
        }
    });
    jListDt.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
        public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
            jListDtValueChanged(evt);
        }
    });
    jScrollPane1.setViewportView(jListDt);

    jLabel13.setText("Rut");

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldApellidoMatDt, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                .addComponent(jTextFieldApellidoDt)))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel13))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldNombreDt)
                                .addComponent(jTextFieldRutDt, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)))))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(477, Short.MAX_VALUE))
    );
    jPanel5Layout.setVerticalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addGap(48, 48, 48)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel13)
                .addComponent(jTextFieldRutDt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel10)
                .addComponent(jTextFieldNombreDt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel11)
                .addComponent(jTextFieldApellidoDt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel12)
                .addComponent(jTextFieldApellidoMatDt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton4)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(171, Short.MAX_VALUE))
    );

    jTabbedPane1.addTab("Director Tecnico", jPanel5);

    jComboBoxEquipoVs1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    jComboBoxEquipoVs1.addItemListener(new java.awt.event.ItemListener() {
        public void itemStateChanged(java.awt.event.ItemEvent evt) {
            jComboBoxEquipoVs1ItemStateChanged(evt);
        }
    });
    jComboBoxEquipoVs1.addInputMethodListener(new java.awt.event.InputMethodListener() {
        public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            jComboBoxEquipoVs1CaretPositionChanged(evt);
        }
        public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
        }
    });

    jComboBoxEquipoVs2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    jComboBoxEquipoVs2.addItemListener(new java.awt.event.ItemListener() {
        public void itemStateChanged(java.awt.event.ItemEvent evt) {
            jComboBoxEquipoVs2ItemStateChanged(evt);
        }
    });

    jLabel18.setText("V/S");

    jListJugadorPartido1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
        public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
            jListJugadorPartido1ValueChanged(evt);
        }
    });
    jScrollPane7.setViewportView(jListJugadorPartido1);

    jListJugadorPartido2.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
        public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
            jListJugadorPartido2ValueChanged(evt);
        }
    });
    jScrollPane8.setViewportView(jListJugadorPartido2);

    jLabel14.setText("00");

    jLabel15.setText("00");

    jLabel16.setText(":");

    jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel17.setText("Fecha");

    jComboBoxPartidoJugado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01/01/2016 - UNIVERSIDAD DE CHILE VS COLO COLO", "Item 2", "Item 3", "Item 4" }));

    jLabel19.setText("Partidos Jugados");

    jButton3.setText("Jugar");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton3ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextField1)
                                    .addGap(10, 10, 10))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGap(32, 32, 32)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jLabel15))))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGap(52, 52, 52)
                                            .addComponent(jButton3)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jComboBoxEquipoVs1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxEquipoVs2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(333, 333, 333)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel19)
            .addGap(18, 18, Short.MAX_VALUE)
            .addComponent(jComboBoxPartidoJugado, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(25, 25, 25))
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addGap(28, 28, 28)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jComboBoxPartidoJugado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel19))
            .addGap(30, 30, 30)
            .addComponent(jLabel18)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jComboBoxEquipoVs1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jComboBoxEquipoVs2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel14)
                .addComponent(jLabel15)
                .addComponent(jLabel16))
            .addGap(26, 26, 26)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jLabel17)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(34, 34, 34)
                    .addComponent(jButton3))
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(79, Short.MAX_VALUE))
    );

    jTabbedPane1.addTab("Partidos", jPanel3);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jTabbedPane1)
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jTabbedPane1)
            .addContainerGap())
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldrutJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldrutJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldrutJugadorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

         if(RutUtil.validaRut(jTextFieldrutJugador.getText())){  
        
            
         String tipo =jComboBoxTipo.getSelectedItem().toString();
        switch(tipo){
    
        case "Arquero":
            
          Arquero arquero=new Arquero();
          arquero.setRut(jTextFieldrutJugador.getText());
          arquero.setNombres(jTextFieldNombres.getText());
          arquero.setApellidoPaterno(jTextFieldApellidoPat.getText());
          arquero.setApellidoMaterno(jTextFieldApellidoMat.getText());
          arquero.setNumero(Integer.parseInt(jTextFieldrutNumero.getText()));    
          arquero.setTitular(jCheckBoxTitular.isSelected());
          JugadoresController.getInstance().agregarArquero(arquero, jComboBoxEquipo.getSelectedIndex());
          JugadoresController.getInstance().doTableJugadores(jTableJugadores);
    
        break;
        
        case "Defensa":
            
          Defensa defensa=new Defensa();
          defensa.setRut(jTextFieldrutJugador.getText());
          defensa.setNombres(jTextFieldNombres.getText());
          defensa.setApellidoPaterno(jTextFieldApellidoPat.getText());
          defensa.setApellidoMaterno(jTextFieldApellidoMat.getText());
          defensa.setNumero(Integer.parseInt(jTextFieldrutNumero.getText()));    
          defensa.setTitular(jCheckBoxTitular.isSelected());
          JugadoresController.getInstance().agregarDefensa(defensa, jComboBoxEquipo.getSelectedIndex());
          JugadoresController.getInstance().doTableJugadores(jTableJugadores);   
            
        break;
        
        case "Volante":
          Volante volante=new Volante();
          volante.setRut(jTextFieldrutJugador.getText());
          volante.setNombres(jTextFieldNombres.getText());
          volante.setApellidoPaterno(jTextFieldApellidoPat.getText());
          volante.setApellidoMaterno(jTextFieldApellidoMat.getText());
          volante.setNumero(Integer.parseInt(jTextFieldrutNumero.getText()));    
          volante.setTitular(jCheckBoxTitular.isSelected());
          JugadoresController.getInstance().agregarVolante(volante, jComboBoxEquipo.getSelectedIndex());
          JugadoresController.getInstance().doTableJugadores(jTableJugadores);     
            
        break;
    
         case "Delantero":
            
          Delantero delantero=new Delantero();
          delantero.setRut(jTextFieldrutJugador.getText());
          delantero.setNombres(jTextFieldNombres.getText());
          delantero.setApellidoPaterno(jTextFieldApellidoPat.getText());
          delantero.setApellidoMaterno(jTextFieldApellidoMat.getText());
          delantero.setNumero(Integer.parseInt(jTextFieldrutNumero.getText()));    
          delantero.setTitular(jCheckBoxTitular.isSelected());
          JugadoresController.getInstance().agregarDelantero(delantero, jComboBoxEquipo.getSelectedIndex());
          JugadoresController.getInstance().doTableJugadores(jTableJugadores);   
             
        break;
    }
          


          }else{
          
             mensajeUtil.setWarningMsg("El Rut Ingresado es invalido.");
          }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombresActionPerformed

    private void jTextFieldApellidoPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellidoPatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellidoPatActionPerformed

    private void jTextFieldApellidoMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellidoMatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellidoMatActionPerformed

    private void jTextFieldrutNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldrutNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldrutNumeroActionPerformed

    private void jComboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoActionPerformed

    private void jCheckBoxTitularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTitularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxTitularActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        
        // crea el objeto equipo y carga las variables
        Equipo objEquipo=new Equipo();
        objEquipo.setNombre(jTextFieldNombreEquipo.getText());
        
        //agreag director tecnico seleccionado al equipo
        objEquipo.setDirectorTecnico(DirectorTecnicoController.getInstance().getDirectorTecnico(jComboBoxDirectorTecnico.getSelectedIndex()));
        
        //agrega el equipo al controlador y luego lo guarda serializado 
        EquipoController.getInstance().agregaEquipo(objEquipo);
        
        //recarga todo los elementos que despliegan datos por pantalla
        cargaInicial();
        
        //mensaje de información
        mensajeUtil.setMsg("Equipo Agregado Correctamente");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    if(RutUtil.validaRut(jTextFieldRutDt.getText())){
    
        // crea el objeto DT con sus datos correspondientes       
        DirectorTecnico objDT = new DirectorTecnico();
        objDT.setRut(jTextFieldRutDt.getText());
        objDT.setNombre(jTextFieldNombreDt.getText());
        objDT.setApellidoPat(jTextFieldApellidoDt.getText());
        objDT.setApellidoMat(jTextFieldApellidoMatDt.getText());
       
        //serializa el objeto DT y lo guarda en un archivo tipo
        DirectorTecnicoController.getInstance().agregarDT(objDT);
        //jListDt.setModel(DirectorTecnicoController.getInstance().getLlistModel());
        //jComboBoxDirectorTecnico.setModel(DirectorTecnicoController.getInstance().getComboBoxModel());       
        //jListEquipos.setModel(EquipoController.getInstance().getLlistModel());
        
        cargaInicial();
     mensajeUtil.setMsg("DT Agregado Correctamente");
    }else{
        mensajeUtil.setWarningMsg("El Rut Ingresado es invalido.");
    }
        
 

// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

   public void cargaInicial(){
    
    jListDt.setModel(DirectorTecnicoController.getInstance().getLlistModel());
    jComboBoxDirectorTecnico.setModel(DirectorTecnicoController.getInstance().getComboBoxModel());
    jComboBoxEquipoVs1.setModel(EquipoController.getInstance().getComboBoxModel());
    jComboBoxEquipoVs2.setModel(EquipoController.getInstance().getComboBoxModel());
    jListEquipos.setModel(EquipoController.getInstance().getLlistModel());
    jComboBoxEquipo.setModel(EquipoController.getInstance().getComboBoxModel());    
    JugadoresController.getInstance().doTableJugadores(jTableJugadores);
     jListJugadorPartido2.setModel(JugadoresController.getInstance().getListTitularesModel(0));
     jListJugadorPartido1.setModel(JugadoresController.getInstance().getListTitularesModel(0));
    
    
    
   }
    
    private void jListDtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jListDtFocusGained
        // TODO add your handling code here:
        
     
    }//GEN-LAST:event_jListDtFocusGained

    private void jListDtValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListDtValueChanged
      if (!evt.getValueIsAdjusting()) {
        JList list = (JList) evt.getSource();
        DirectorTecnico dt= DirectorTecnicoController.getInstance().getDirectorTecnico(list.getAnchorSelectionIndex());  
             
         jTextFieldRutDt.setText(dt.getRut());
         jTextFieldNombreDt.setText(dt.getNombre());
         jTextFieldApellidoDt.setText(dt.getApellidoPat());
         jTextFieldApellidoMatDt.setText(dt.getApellidoMat());
       
           }
        
        
    }//GEN-LAST:event_jListDtValueChanged

    private void jListDtPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jListDtPropertyChange
       // TODO add your handling code here:
    }//GEN-LAST:event_jListDtPropertyChange

    private void jListEquiposValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListEquiposValueChanged

      if (!evt.getValueIsAdjusting()) {
        JList list = (JList) evt.getSource();
        Equipo equipo= EquipoController.getInstance().getEquipo(list.getAnchorSelectionIndex());  
        
        if(equipo!=null){
         jTextFieldNombreEquipo.setText(equipo.getNombre());
         jComboBoxDirectorTecnico.setSelectedItem(equipo.getDirectorTecnico().getNombre()+" "+equipo.getDirectorTecnico().getApellidoPat()+" "+equipo.getDirectorTecnico().getApellidoMat());
         JugadoresController.getInstance().doTableJugadores(jTableJugadores1,list.getSelectedIndex()); 
         
        }
          }

       
    }//GEN-LAST:event_jListEquiposValueChanged

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
       
        EquipoController.getInstance().eliminaEquipo(jTextFieldNombreEquipo.getText());
        jListEquipos.setModel(EquipoController.getInstance().getLlistModel());
        jTextFieldNombreEquipo.setText("");
        cargaInicial();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jListJugadorPartido1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListJugadorPartido1ValueChanged
 if (!evt.getValueIsAdjusting()) {
     
    String indexJugador=jListJugadorPartido1.getSelectedValue();
     
    DetalleJugador detJugador = new DetalleJugador();
    detJugador.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    detJugador.pack();
    detJugador.setVisible(true);
 }
        // TODO add your handling code here:
    }//GEN-LAST:event_jListJugadorPartido1ValueChanged

    private void jListJugadorPartido2ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListJugadorPartido2ValueChanged
   
     if (!evt.getValueIsAdjusting()) {    
    DetalleJugador detJugador = new DetalleJugador();
    detJugador.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    detJugador.pack();
    detJugador.setVisible(true);       
     }
    }//GEN-LAST:event_jListJugadorPartido2ValueChanged

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:}
        
        
        String rut= jTableJugadores.getModel().getValueAt(jTableJugadores.getSelectedRow(), 0).toString();
        JugadoresController.getInstance().EliminaJugador(rut);
        JugadoresController.getInstance().doTableJugadores(jTableJugadores); 
        cargaInicial();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBoxEquipoVs1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxEquipoVs1ItemStateChanged

    int index=jComboBoxEquipoVs1.getSelectedIndex();
    jListJugadorPartido1.setModel(JugadoresController.getInstance().getListTitularesModel(index));
   

        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEquipoVs1ItemStateChanged

    private void jComboBoxEquipoVs1CaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jComboBoxEquipoVs1CaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEquipoVs1CaretPositionChanged

    private void jComboBoxEquipoVs2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxEquipoVs2ItemStateChanged
        // TODO add your handling code here:
        
    int index=jComboBoxEquipoVs2.getSelectedIndex();
    jListJugadorPartido2.setModel(JugadoresController.getInstance().getListTitularesModel(index));
    }//GEN-LAST:event_jComboBoxEquipoVs2ItemStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(appPartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(appPartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(appPartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(appPartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new appPartido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBoxTitular;
    private javax.swing.JComboBox<String> jComboBoxDirectorTecnico;
    private javax.swing.JComboBox<String> jComboBoxEquipo;
    private javax.swing.JComboBox<String> jComboBoxEquipoVs1;
    private javax.swing.JComboBox<String> jComboBoxEquipoVs2;
    private javax.swing.JComboBox<String> jComboBoxPartidoJugado;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jListDt;
    private javax.swing.JList<String> jListEquipos;
    private javax.swing.JList<String> jListJugadorPartido1;
    private javax.swing.JList<String> jListJugadorPartido2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTableJugadores;
    private javax.swing.JTable jTableJugadores1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldApellidoDt;
    private javax.swing.JTextField jTextFieldApellidoMat;
    private javax.swing.JTextField jTextFieldApellidoMatDt;
    private javax.swing.JTextField jTextFieldApellidoPat;
    private javax.swing.JTextField jTextFieldNombreDt;
    private javax.swing.JTextField jTextFieldNombreEquipo;
    private javax.swing.JTextField jTextFieldNombres;
    private javax.swing.JTextField jTextFieldRutDt;
    private javax.swing.JTextField jTextFieldrutJugador;
    private javax.swing.JTextField jTextFieldrutNumero;
    // End of variables declaration//GEN-END:variables
}
